apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-rbac
rules:
- apiGroups: [""]  
  resources: ["pods","services"]
  verbs: ["get","list","watch"]
- apiGroups: ["apps"]  
  resources: ["deployments"]
  verbs: ["get","list","watch"]