apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-rbac-binding
subjects:
- kind: ServiceAccount
  name: gitlab-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: gitlab-cluster-role
  apiGroup: rbac.authorization.k8s.io